export const clerkAppearance = {
  variables: {
    colorPrimary: "#e0a531",
    colorBackground: "#17130f",
    colorText: "#f3eee4",
    colorTextSecondary: "#9b9184",
    colorTextOnPrimaryBackground: "#171104",
    colorInputBackground: "#100e0b",
    colorInputText: "#f3eee4",
    colorNeutral: "#f3eee4",
    colorDanger: "#c9503e",
    colorSuccess: "#82ab45",
    colorWarning: "#d98c2b",
    colorShimmer: "rgba(224,165,49,0.16)",
    borderRadius: "0.625rem",
    fontFamily: "inherit",
    fontSize: "0.9rem",
  },
  elements: {
    modalBackdrop: { backgroundColor: "rgba(6,5,4,0.72)" },
    card: {
      backgroundColor: "#17130f",
      border: "1px solid #2f2820",
      boxShadow: "0 24px 60px rgba(0,0,0,0.55)",
    },
    cardBox: { border: "1px solid #2f2820", boxShadow: "none" },
    headerTitle: { color: "#f3eee4", letterSpacing: "-0.01em" },
    headerSubtitle: { color: "#9b9184" },
    socialButtonsBlockButton: {
      backgroundColor: "#221c15",
      border: "1px solid #2f2820",
      color: "#f3eee4",
    },
    socialButtonsBlockButtonText: { color: "#f3eee4", fontWeight: 500 },
    dividerLine: { backgroundColor: "#2f2820" },
    dividerText: { color: "#9b9184" },
    formFieldLabel: { color: "#9b9184" },
    formFieldInput: {
      backgroundColor: "#100e0b",
      border: "1px solid #2f2820",
      color: "#f3eee4",
    },
    formButtonPrimary: {
      backgroundColor: "#e0a531",
      color: "#171104",
      fontWeight: 600,
      textTransform: "none",
      boxShadow: "none",
    },
    footer: { background: "none", borderTop: "1px solid #2f2820" },
    footerAction: { background: "none" },
    footerActionText: { color: "#9b9184" },
    footerActionLink: { color: "#e0a531", fontWeight: 500 },
    identityPreviewText: { color: "#f3eee4" },
    identityPreviewEditButtonIcon: { color: "#e0a531" },
    formResendCodeLink: { color: "#e0a531" },
    otpCodeFieldInput: {
      backgroundColor: "#100e0b",
      border: "1px solid #2f2820",
      color: "#f3eee4",
    },
    userButtonPopoverCard: {
      backgroundColor: "#17130f",
      border: "1px solid #2f2820",
    },
    userButtonPopoverActionButton: { color: "#f3eee4" },
    userButtonPopoverActionButtonText: { color: "#f3eee4" },
    userButtonPopoverFooter: { display: "none" },
    badge: {
      backgroundColor: "#221c15",
      color: "#9b9184",
      border: "1px solid #2f2820",
    },
    logoBox: { display: "none" },
  },
  layout: {
    socialButtonsVariant: "blockButton",
    shimmer: false,
  },
} as const;
